language: generic

services:
  - docker

env:
  global:
    # In order to report exit code
    - BUILD_ENV=1

before_install:
  - bin/d up
  - bin/d ls -la
  - docker ps -a

script:
  - RAILS_ENV=test bin/d bundle exec rake db:drop db:create db:migrate
  - RAILS_ENV=test bin/d bundle exec rspec

#deploy:
#  provider: script
#  script: bash scripts/docker_push