language: ruby
rvm:
  - 2.5.6
cache: bundler
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test
notifications:
  email: false
  webhooks: https://hooks.zapier.com/hooks/catch/2532206/wbitzc/
  on_success: change
  on_failure: always
