language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    # In order to have scripts know that we are in build/CI mode
    - BUILD_ENV=1

before_install:
  - bin/d up
  - bin/d ls -la
  - docker ps -a

script:
  - RAILS_ENV=test bin/d bundle exec rake db:drop db:create db:migrate
  - RAILS_ENV=test bin/d bundle exec rspec

# We don't use deploy anymore as it triggers only on success
# while we want to be able to deploy despite failing tests is some situations
# (e.g. on staging currently)

# deploy:
#   provider: script
#   script: sh scripts/deploy_ecr.sh
#   on:
#     branch: staging
#     # all_branches: true

after_script:
  - if bash scripts/travis_should_deploy.sh; then sh scripts/deploy_ecr.sh; fi
