dry-run: null
hookfiles: ./dredd/hooks/*.js
sandbox: false
server: bundle exec rails s -p3210
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: [junit]
output: [./dredd/output/report.xml]
header: []
sorted: true
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: ./entourage.apib
endpoint: 'http://localhost:3210'
