dry-run: null
hookfiles: ./dredd/hooks.js
sandbox: false
server: bundle exec rails s
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: true
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: ./api.md
endpoint: 'http://localhost:3000'
