dry-run: null
hookfiles: ./dredd/hooks/trailing_new_line.js
sandbox: false
server: bundle exec rails s -p 3001
server-wait: 5
init: false
custom: {}
names: false
only: []
reporter: [junit]
output: [./dredd/output/report.xml]
header: []
sorted: true
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: ./api.md
endpoint: 'http://localhost:3001'
