development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("HEROKU_REDIS_GOLD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: entourage_back_production
  ssl_params: { verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> }
