default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV['MAX_THREADS'] || 5 %>
  timeout: 5000
  username: entourage
  password:

development:
  <<: *default
  database: entourage-dev

test:
  <<: *default
  database: entourage-test

production:
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  pool: <%= ENV['MAX_THREADS'] || 5 %>
  prepared_statements: false