class CreateEntourageAreas < ActiveRecord::Migration[6.1]
  def up
    create_table :entourage_areas do |t|
      t.string :postal_code
      t.boolean :antenne
      t.string :geo_zone
      t.string :display_name
      t.string :city

      t.timestamps
    end

    unless Rails.env.test?
      EntourageArea.create( postal_code: '00', antenne: true, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '01', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '02', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '03', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '04', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '05', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '06', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '07', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '08', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '09', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '10', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '11', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '12', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '13', antenne: true, geo_zone: 'PACA', display_name: 'PACA (Marseille)', city: 'Marseille')
      EntourageArea.create( postal_code: '14', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '15', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '16', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '17', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '18', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '19', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '20', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '21', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '22', antenne: true, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '23', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '24', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '25', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '26', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '27', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '28', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '29', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '30', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '31', antenne: true, geo_zone: 'Grand Ouest', display_name: 'Grand Ouest (Toulouse)', city: 'Toulouse')
      EntourageArea.create( postal_code: '32', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '33', antenne: true, geo_zone: 'Grand Ouest', display_name: 'Grand Ouest (Bordeaux)', city: 'Bordeaux')
      EntourageArea.create( postal_code: '34', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '35', antenne: true, geo_zone: 'Bretagne', display_name: 'Bretagne (Rennes)', city: 'Rennes')
      EntourageArea.create( postal_code: '35288', antenne: false, geo_zone: 'Bretagne', display_name: 'Bretagne (Saint-Malo)', city: 'Saint-Malo')
      EntourageArea.create( postal_code: '36', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '37', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '38', antenne: true, geo_zone: 'AURA', display_name: 'AURA (Grenoble)', city: 'Grenoble')
      EntourageArea.create( postal_code: '39', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '40', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '41', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '42', antenne: true, geo_zone: 'AURA', display_name: 'AURA (Saint-Etienne)', city: 'Saint-Etienne')
      EntourageArea.create( postal_code: '43', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '44', antenne: true, geo_zone: 'Bretagne', display_name: 'Bretagne (Nantes)', city: 'Nantes')
      EntourageArea.create( postal_code: '45', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '46', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '47', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '48', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '49', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '50', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '51', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '52', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '53', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '54', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '55', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '56', antenne: true, geo_zone: 'Bretagne', display_name: 'Bretagne (Lorient)', city: 'Lorient')
      EntourageArea.create( postal_code: '57', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '58', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '59', antenne: true, geo_zone: 'Nord', display_name: 'Nord (Lille)', city: 'Lille')
      EntourageArea.create( postal_code: '59100', antenne: false, geo_zone: 'Nord', display_name: 'Nord (Roubaix)', city: 'Roubaix')
      EntourageArea.create( postal_code: '60', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '61', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '62', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '63', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '64', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '65', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '66', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '67', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '68', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '69', antenne: true, geo_zone: 'AURA', display_name: 'AURA (Lyon)', city: 'Lyon')
      EntourageArea.create( postal_code: '70', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '71', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '72', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '73', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '74', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '75', antenne: true, geo_zone: 'IDF', display_name: 'IDF (Paris)', city: 'Paris')
      EntourageArea.create( postal_code: '76', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '77', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '78', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '79', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '80', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '81', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '82', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '83', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '84', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '85', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '86', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '87', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '88', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '89', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '90', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '91', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '92', antenne: true, geo_zone: 'IDF', display_name: 'IDF (Hauts de Seine)', city: 'Hauts de Seine')
      EntourageArea.create( postal_code: '93', antenne: true, geo_zone: 'IDF', display_name: 'IDF (Seine Saint-Denis)', city: 'Seine Saint Denis')
      EntourageArea.create( postal_code: '94', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '95', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '96', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '97', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '98', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
      EntourageArea.create( postal_code: '99', antenne: false, geo_zone: 'Hors Zone', display_name: 'Hors Zone', city: 'Hors Zone')
    end
  end

  def down
    drop_table :entourage_areas
  end
end
