chaleur_humaine:
  name: "Vidéo Entourage, un peu de chaleur humaine"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=IYUo5WAZxXs
  duration: 96
  is_video: true
  status: active

adresses_solidaires:
  name: "Article présentation carte POIs : où trouver des adresses solidaires pour m'aider ?"
  category: understand
  description: description
  url: https://blog.entourage.social/2020/11/10/comment-trouver-les-bonnes-adresses-et-demarches-a-faire-quand-on-est-sdf-ou-precaire/
  duration: 60
  is_video: false
  status: active

aides_sociales:
  name: "Article Aides sociales : comment y avoir accès ?"
  category: understand
  description: description
  url: https://blog.entourage.social/2020/11/06/les-aides-sociales-en-france-comment-y-avoir-acces-quand-on-est-sdf/
  duration: 300
  is_video: false
  status: active

comite_de_la_rue:
  name: "Vidéo Le Comité de la Rue, organe essentiel d'Entourage"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=CaTIbs03TQ0
  duration: 141
  is_video: true
  status: active

idees_d_actions:
  name: "Article Des idées d'actions faciles à réaliser sur l'app !"
  category: act
  description: description
  url: https://blog.entourage.social/2017/04/28/quelles-actions-faire-avec-entourage/
  duration: 180
  is_video: false
  status: active

devenir_sdf:
  name: "Vidéo Comment devient-on SDF ?"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=Dk3bo__5dvs
  duration: 154
  is_video: true
  status: active

si_on_se_comprenait:
  name: "Vidéo SDF, et si on comprenait ?"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=aVobOfVgELg
  duration: 198
  is_video: true
  status: active

combat_d_eric:
  name: "Vidéo Loopsider Le combat d'Eric, sans-abri à Paris"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=kUHJqJ-FifU
  # duration: 120
  is_video: 407
  status: active

wifi:
  name: "Vidéo J'ai ouvert mon WiFi à mes voisins"
  category: inspire
  description: description
  url: https://www.youtube.com/watch?v=lZxLhBDj8Kk
  duration: 129
  is_video: true
  status: active

si_on_changeait_de_regard:
  name: "Vidéo Personnes sans-domicile-fixe : et si on changeait de regard ?"
  category: inspire
  description: description
  url: https://www.youtube.com/watch?v=hemPKnpsfWc
  duration: 197
  is_video: true
  status: active

paroles_de_femmes:
  name: "Vidéo Paroles de femmes sans-domicile-fixe"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=kF7CnsSsBxE
  duration: 133
  is_video: true
  status: active

rachid_et_marie:
  name: "Vidéo Regards croisés : Rachid & Marie"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=QXcUptypnOY
  duration: 124
  is_video: true
  status: active

urgence_sociale:
  name: "Vidéo L'urgence sociale : qui fait quoi ?"
  category: understand
  description: description
  url: https://www.youtube.com/watch?v=DiJf64CtZRc
  duration: 201
  is_video: true
  status: active

si_on_agissait:
  name: "Vidéo Personnes sans-domicile-fixe : et si on agissait ?"
  category: act
  description: description
  url: https://www.youtube.com/watch?v=SvYCZ3s0AFE
  duration: 270
  is_video: true
  status: active

tuto_evenement:
  name: "Tuto app - Comment créer un événement ?"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: true
  status: active

tuto_groupe:
  name: "Tuto app - Comment créer un groupe ?"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: true
  status: active

preparer_la_rencontre:
  name: "Préparer la rencontre"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: true
  status: active

tuto_don:
  name: "Tuto ce que je peux donner / ne pas donner"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: true
  status: active

charte_ethique:
  name: "La Charte éthique en qlq mots"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: true
  status: active

relayer_les_demandes:
  name: "Article “Comment relayer les demandes à son réseau de quartier”"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: false
  status: active

maraudes:
  name: "Article Les maraudes pour les nuls"
  category: act
  description: description
  url: https://blog.entourage.social/2021/04/26/maraude-pour-les-nuls/
  duration: 300
  is_video: false
  status: active

pyramide_de_maslow:
  name: "Article La pyramide de Maslow : une vision biaisée de l'homme ?"
  category: understand
  description: description
  url: https://blog.entourage.social/2022/02/24/la-pyramide-de-maslow-une-vision-biaisee-de-lhomme/
  duration: 60
  is_video: false
  status: active

portrait_de_benevole:
  name: "Vidéo Audrey dans les portraits de bénévoles"
  category: inspire
  description: description
  url: https://www.youtube.com/watch?v=zNF9QaUpvn8
  duration: 66
  is_video: true
  status: active

communaute:
  name: "Article Faire grandir la communauté Entourage"
  category: act
  description: description
  # url:
  # duration: 120
  is_video: false
  status: active

